eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
            ---
      spring:
        profiles: peer
      eureka:
        instance:
          hostname: ${APP_NAME}.herokuapp.com
        client:
          registerWithEureka: true
          fetchRegistry: true
          serviceUrl:
            defaultZone: ${EUREKA_PEER_URL}/eureka/
